#!/usr/bin/env sh

echo "🧪 Running pre-commit checks..."
echo "-------------------------------"
echo

error=0

echo "🔍 Type checking..."
npm run typecheck
if [ $? -ne 0 ]; then
  echo
  echo "❌ TypeScript type errors detected."
  error=1
fi

echo
echo "🎨 Formatting, sorting imports & linting staged files..."
npx lint-staged
if [ $? -ne 0 ]; then
  echo
  echo "❌ Linting or formatting failed."
  error=1
fi

if [ $error -ne 0 ]; then
  echo
  echo "❌ Commit aborted."
  exit 1
fi

echo
echo "✅ All pre-commit checks passed!"